name: shared_audio_utils
description: Generic interface for audio playback.
version: 0.2.0
repository: https://github.com/nmfisher/shared_audio_utils

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  logging: ^1.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
