name: shared_audio_utils
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/nmfisher/shared_audio_utils

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
